# Service to save and execute a job in the database

# Id of the job to be executed
string uuid
---
# Whether the job has been executed successfully
bool success false
# Confirmation or error message
string message "Unexpected Error. Response message not set."
